# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(max_length=128)),
                ('auth', models.CharField(max_length=32)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
