# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180428_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
