# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180428_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='read_state',
            field=models.IntegerField(default=0),
        ),
    ]
